name: Exportar Dados Prolog

on:
  schedule:
    # Rodar às 07:30 (10:30 UTC)
    - cron: '30 10 * * *'
    # Rodar às 13:00 (16:00 UTC)
    - cron: '0 16 * * *'
  workflow_dispatch:  # Permite disparar manualmente também

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clonar o repositório
      - name: Clonar o repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar ambiente virtual e instalar dependências
      - name: Configurar Ambiente Virtual e Instalar Dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 3: Executar o script Python com as variáveis de ambiente
      - name: Executar script de exportação
        run: |
          source venv/bin/activate
          python src/main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
