name: Exportar Dados Prolog

on:
  schedule:
    # Rodar às 07h horário de Brasília (UTC-3)
    - cron: '0 10 * * *'  # 07h de Brasília (UTC-3)
  workflow_dispatch:  # Permite disparar manualmente também

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clonar o repositório
      - name: Clonar o repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar ambiente virtual e instalar dependências
      - name: Configurar Ambiente Virtual e Instalar Dependências
        run: |
          python -m venv venv  # Cria o ambiente virtual
          source venv/bin/activate  # Ativa o ambiente virtual
          pip install --upgrade pip  # Atualiza o pip
          pip install -r requirements.txt  # Instala as dependências do requirements.txt

      # Passo 3: Executar o script Python com as variáveis de ambiente
      - name: Executar script de exportação
        run: |
          source venv/bin/activate  # Ativa o ambiente virtual
          python src/main.py  # Executa o script Python
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
