name: Run Python Script

on:
  push:
    branches:
      - main  # Ou a branch onde você deseja rodar o script
  pull_request:
    branches:
      - main  # Ou a branch onde você deseja rodar o script

jobs:
  run-script:
    runs-on: ubuntu-latest  # Utilizando Ubuntu para rodar o script

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Faz o checkout do código no repositório

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Escolha a versão do Python que você usa

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se você tiver um arquivo requirements.txt

    - name: Run script
      run: |
        python src/main.py  # Caminho para rodar seu script
